const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8")
    .replace(/\r\n?/g, "\n")
    .replace(/^\/\*[^\n]*generated[^\n]*\*\/\s*/i, "");
}

function lines(relativePath) {
  return read(relativePath).split("\n");
}

function accountStyles() {
  const source = read("css/pages/account.css");
  const legacyStartMarker = ".vip-grid{grid-template-columns:repeat(auto-fill,minmax(235px,1fr));gap:20px}";
  const legacyEndMarker = ".perk-box{";
  const legacyStart = source.indexOf(legacyStartMarker);
  const legacyEnd = source.indexOf(legacyEndMarker, legacyStart);
  if (legacyStart === -1 || legacyEnd === -1) {
    throw new Error("Missing legacy VIP boundaries in css/pages/account.css");
  }
  return source.slice(0, legacyStart) + source.slice(legacyEnd);
}

const base = lines("css/core/base.css");
function sectionIndex(label) {
  const index = base.findIndex((line) => line.includes(label));
  if (index === -1) {
    throw new Error(`Missing css/core/base.css section: ${label}`);
  }
  return index;
}

// base.css contains four pieces of the former monolith. Put them back around
// the page/game sections so the original cascade remains intact. Section
// markers keep this stable when core styles gain or lose lines.
const resetStart = sectionIndex("── RESET");
const overlaysStart = sectionIndex("── MODAL");
const sharedShellStart = sectionIndex("── SHARED PAGE SHELL");
const baseTokens = base.slice(2, resetStart).join("\n");
const baseShell = base.slice(resetStart, overlaysStart).join("\n");
const baseOverlays = base.slice(overlaysStart, sharedShellStart).join("\n");
const baseResponsive = base.slice(sharedShellStart).join("\n");

const sections = [
  baseTokens,
  baseShell,
  read("css/pages/home.css"),
  baseOverlays,
  accountStyles(),
  read("css/games/roulette.css"),
  read("css/games/lucky-bamboo.css"),
  read("css/games/kawaui-fortune.css"),
  read("css/games/eclipse-hunt.css"),
  read("css/games/neon-pyramids.css"),
  read("css/pages/admin.css"),
  read("css/pages/help.css"),
  read("css/games/texas-holdem.css"),
  read("css/games/midnight-vault.css"),
  baseResponsive,
  read("css/games/arctic-protocol.css"),
  read("css/games/shared.css"),
  read("css/pages/profile.css"),
  read("css/pages/cashier.css"),
];

const banner = "/* Bambiku restored compatibility bundle. Generated by scripts/build-css.js. */\n\n";
const bundle = sections.join("\n\n")
  .replace(/\r/g, "")
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/^[\t ]+/gm, "")
  .replace(/[\t ]+\n/g, "\n")
  .replace(/\n[\t ]*\n+/g, "\n")
  .replace(/([{},;])\n/g, "$1")
  .replace(/\n/g, "")
  .replace(/\s*([{},;])\s*/g, "$1")
  .replace(/([;{])([-\w]+):\s+/g, "$1$2:")
  .replace(/;}/g, "}")
  .replace(/([:,( ])(-?)0\.(\d+)/g, "$1$2.$3")
  .replace(/([:,( ])0(?:px|em|rem|vh|vw|vmin|vmax|cm|mm|in|pt|pc|ex|ch)\b/gi, (_, prefix) => `${prefix}0`);
fs.writeFileSync(path.join(root, "css/style.css"), banner + bundle, "utf8");
console.log("Built css/style.css");
